### PR TITLE
added-gymsoProject

### PR DESCRIPTION
**Pull request by Surieya**

### CODE REVIEW

**Comment by Surieya** [comment]
could you please check and merge my PR @Niraj-1729

**Comment by Niraj-1729** [comment]
add locally hosted link in comment

**Comment by Surieya** [comment]
Here is the link 
https://surieya.github.io/GymWebsite/
@Niraj-1729

**Comment by Surieya** [comment]
@Niraj-1729  this MR is Excluded by the hacktoberfest could you please tell me the reason?

**Pull request merged**
