### PR TITLE
Event Organizing Website

### PR DESCRIPTION
**Pull request by surajvast1**

### CODE REVIEW

**Comment by surajvast1** [comment]
created a new project merge this please

**Comment by Niraj-1729** [comment]
I have assigned this to you,
but I'll merge only after existing issues gets resolved.
Don't forget to star this repo for being at highest consideration.

**Comment by surajvast1** [comment]
I am unaware of the issues you are talking about can you explain in detail please

**Comment by surajvast1** [comment]
Yaa sure I gave a start Thanks a lot!

**Pull request merged**
